server:
  port: 8080

gateway:
  rate-limit:
    enabled: true
  health-check:
    enabled: true
    interval: 10s
    timeout: 2s
  routes:
    - id: user-service
      pathPattern: /api/v1/users/**
      targetUris:
        - http://localhost:8081
        - http://localhost:8082
        - http://localhost:8083
      healthCheckPath: /actuator/health
      stripPrefix: 2
      order: 1
      replenishRate: 1
      burstCapacity: 2
      requiresAuth: true
      circuitBreakerEnabled: true
    - id: order-service
      pathPattern: /api/v1/orders/**
      targetUri: http://localhost:8082
      stripPrefix: 2
      order: 2
    - id: catch-all
      pathPattern: /api/v1/**
      targetUri: http://localhost:8083
      stripPrefix: 0
      order: 100

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
    instances:
      user-service:
        baseConfig: default

logging:
  level:
    root: INFO
    com.apigateway: DEBUG